config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :periods
  resources :transactions do
    collection do
      post :import
    end
  end
  resources :memberships
  resources :membership_types
  resources :accounts
  resources :member_groups
  resources :invoices
  resources :members do
    collection do
      post :import
    end
  end
  resources :organisations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :organisation
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :bankaccountable, polymorphic: true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :account
  belongs_to :period
  belongs_to :organisation
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :member
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/mandate.rb
class Mandate < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :organisation
  has_one :adress, as: :addressable
  has_one :bank_account, as: :bankaccountable
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :organisation
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member
  belongs_to :membership_type
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  belongs_to :organisation
end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_one :adress, as: :addressable
    has_one :bank_account, as: :bankaccountable
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :organisation
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :organisation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[ show edit update destroy ]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to memberships_url, notice: "Membership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.require(:membership).permit(:member_id, :membership_type_id, :start_date, :end_date, :renewal_date, :description, :status)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :member_id, class: "label" %>
    <div class="select">
      <%= form.collection_select :member_id, Member.all, :id, :name, { prompt: true }  %>
    </div>
  </div>

  <div class="field">
    <%= form.label :membership_type_id, class: "label" %>
    <div class="select">
      <%= form.collection_select :membership_type_id, MembershipType.all, :id, :name, { prompt: true }  %>
    </div>
  </div>

  <div class="field">
    <%= form.label :start_date, class: "label" %>
    <div class="control">
      <%= form.date_field :start_date, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :end_date, class: "label" %>
    <div class="control">
      <%= form.date_field :end_date, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :renewal_date, class: "label" %>
    <div class="control">
      <%= form.date_field :renewal_date, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_field :description, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :status, class: "label" %>
    <div class="control">
      <%= form.text_field :status, class: "input" %>
    </div>
  </div>

 <div class="field is-grouped">
    <%= link_to "Back", memberships_path, class: "button is-info mr-2" %>
    <%= form.submit class: 'button is-primary' %>  
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Member:</strong>
    <%= membership.member_id %>
  </p>

  <p>
    <strong>Membership type:</strong>
    <%= membership.membership_type_id %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= membership.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= membership.end_date %>
  </p>

  <p>
    <strong>Renewal date:</strong>
    <%= membership.renewal_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= membership.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= membership.status %>
  </p>

</div>

app/views/memberships/edit.html.erb
<div class="container">
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>


</div>

app/views/memberships/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table class="table">
  <thead>
    <tr>
    <th colspan="1"></th>
        <th>Member</th>
      <th>Membership type</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Renewal date</th>
      <th>Description</th>
      <th>Status</th>
      </tr>
  </thead>
  <tbody>
   <% @memberships.each do |membership| %>
        <tr>
          <td>
            <input type="checkbox">
          </td>
            <td><%= membership.member_id %></td>
            <td><%= membership.membership_type_id %></td>
            <td><%= membership.start_date %></td>
            <td><%= membership.end_date %></td>
            <td><%= membership.renewal_date %></td>
            <td><%= membership.description %></td>
            <td><%= membership.status %></td>
          </tr>
      <% end %>
  </tbody>
</table>

 <%= link_to 'New Membership', new_membership_path, class: "button is-succes" %>
</div>

app/views/memberships/new.html.erb
<div class="container">

<h1>New membership</h1>

<%= render "form", membership: @membership %>


</div>

app/views/memberships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>