config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :periods
  resources :transactions do
    collection do
      post :import
    end
  end
  resources :memberships
  resources :membership_types
  resources :accounts
  resources :member_groups
  resources :invoices
  resources :members do
    collection do
      post :import
    end
  end
  resources :organisations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :organisation
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :bankaccountable, polymorphic: true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :account
  belongs_to :period
  belongs_to :organisation
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :member
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/mandate.rb
class Mandate < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :organisation
  has_one :adress, as: :addressable
  has_one :bank_account, as: :bankaccountable
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :organisation
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member
  belongs_to :membership_type
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  belongs_to :organisation
end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_one :adress, as: :addressable
    has_one :bank_account, as: :bankaccountable
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :organisation
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :organisation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/member_groups_controller.rb
class MemberGroupsController < ApplicationController
  before_action :set_member_group, only: %i[ show edit update destroy ]

  # GET /member_groups or /member_groups.json
  def index
    @member_groups = MemberGroup.all
  end

  # GET /member_groups/1 or /member_groups/1.json
  def show
  end

  # GET /member_groups/new
  def new
    @member_group = MemberGroup.new
  end

  # GET /member_groups/1/edit
  def edit
  end

  # POST /member_groups or /member_groups.json
  def create
    @member_group = MemberGroup.new(member_group_params)
    @member_group.Organisation = Organisation.First

    respond_to do |format|
      if @member_group.save
        format.html { redirect_to member_group_url(@member_group), notice: "Member group was successfully created." }
        format.json { render :show, status: :created, location: @member_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /member_groups/1 or /member_groups/1.json
  def update
    respond_to do |format|
      if @member_group.update(member_group_params)
        format.html { redirect_to member_group_url(@member_group), notice: "Member group was successfully updated." }
        format.json { render :show, status: :ok, location: @member_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /member_groups/1 or /member_groups/1.json
  def destroy
    @member_group.destroy

    respond_to do |format|
      format.html { redirect_to member_groups_url, notice: "Member group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_group
      @member_group = MemberGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_group_params
      params.require(:member_group).permit(:name, :description, :price, :organisation_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/member_groups_helper.rb
module MemberGroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/member_groups/_form.html.erb
<%= form_with(model: member_group) do |form| %>
  <% if member_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member_group.errors.count, "error") %> prohibited this member_group from being saved:</h2>

      <ul>
        <% member_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "label" %>
    <div class="control">
      <%= form.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
  <%= form.label :price, class: "label" %>
  <div class="control">
    <%= form.number_field :price, class: "input" %>
  </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_area :description, class: "textarea" %>
    </div>
  </div>



 <div class="field is-grouped">
    <%= link_to "Back", member_groups_path, class: "button is-info mr-2" %>
    <%= form.submit class: 'button is-primary' %>  
  </div>
<% end %>

app/views/member_groups/_member_group.html.erb
<div id="<%= dom_id member_group %>">
  <p>
    <strong>Name:</strong>
    <%= member_group.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= member_group.description %>
  </p>

  <p>
    <strong>Organisation:</strong>
    <%= member_group.organisation_id %>
  </p>

</div>

app/views/member_groups/edit.html.erb
<div class="container">
<h1>Editing member group</h1>

<%= render "form", member_group: @member_group %>


</div>

app/views/member_groups/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Member groups</h1>

<table class="table">
  <thead>
    <tr>
    <th colspan="1"></th>
      <th>Name</th>
      <th>Price</th>
      </tr>
  </thead>
  <tbody>
   <% @member_groups.each do |member_group| %>
        <tr>
          <td>
            <input type="checkbox">
          </td>
            <td><%= link_to member_group.name, edit_member_group_path(member_group.id) %></td>
            <td><%= member_group.price %></td>
          </tr>
      <% end %>
  </tbody>
</table>

 <%= link_to 'New Member Group', new_member_group_path, class: "button is-succes" %>
</div>

app/views/member_groups/new.html.erb
<div class="container">

<h1>New member group</h1>

<%= render "form", member_group: @member_group %>


</div>

app/views/member_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member_group %>

<div>
  <%= link_to "Edit this member group", edit_member_group_path(@member_group) %> |
  <%= link_to "Back to member groups", member_groups_path %>

  <%= button_to "Destroy this member group", @member_group, method: :delete %>
</div>