config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :periods
  resources :transactions do
    collection do
      post :import
    end
  end
  resources :memberships
  resources :membership_types
  resources :accounts
  resources :member_groups
  resources :invoices
  resources :members do
    collection do
      post :import
    end
  end
  resources :organisations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :organisation
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :bankaccountable, polymorphic: true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :account
  belongs_to :period
  belongs_to :organisation
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :member
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/mandate.rb
class Mandate < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :organisation
  has_one :adress, as: :addressable
  has_one :bank_account, as: :bankaccountable
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :organisation
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member
  belongs_to :membership_type
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  belongs_to :organisation
end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_one :adress, as: :addressable
    has_one :bank_account, as: :bankaccountable
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :organisation
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :organisation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/membership_types_controller.rb
class MembershipTypesController < ApplicationController
  before_action :set_membership_type, only: %i[ show edit update destroy ]

  # GET /membership_types or /membership_types.json
  def index
    @membership_types = MembershipType.all
  end

  # GET /membership_types/1 or /membership_types/1.json
  def show
  end

  # GET /membership_types/new
  def new
    @membership_type = MembershipType.new
  end

  # GET /membership_types/1/edit
  def edit
  end

  # POST /membership_types or /membership_types.json
  def create
    @membership_type = MembershipType.new(membership_type_params)

    respond_to do |format|
      if @membership_type.save
        format.html { redirect_to membership_type_url(@membership_type), notice: "Membership type was successfully created." }
        format.json { render :show, status: :created, location: @membership_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /membership_types/1 or /membership_types/1.json
  def update
    respond_to do |format|
      if @membership_type.update(membership_type_params)
        format.html { redirect_to membership_type_url(@membership_type), notice: "Membership type was successfully updated." }
        format.json { render :show, status: :ok, location: @membership_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /membership_types/1 or /membership_types/1.json
  def destroy
    @membership_type.destroy

    respond_to do |format|
      format.html { redirect_to membership_types_url, notice: "Membership type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership_type
      @membership_type = MembershipType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_type_params
      params.require(:membership_type).permit(:code, :description, :price, :organisation_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/membership_types_helper.rb
module MembershipTypesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/views/membership_types/_form.html.erb
<%= form_with(model: membership_type) do |form| %>
  <% if membership_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership_type.errors.count, "error") %> prohibited this membership_type from being saved:</h2>

      <ul>
        <% membership_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code, class: "label" %>
    <div class="control">
      <%= form.text_field :code, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_field :description, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :price, class: "label" %>
    <div class="control">
      <%= form.text_field :price, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :organisation_id, class: "label" %>
    <div class="select">
      <%= form.collection_select :organisation_id, Organisation.all, :id, :name, { prompt: true }  %>
    </div>
  </div>

 <div class="field is-grouped">
    <%= link_to "Back", membership_types_path, class: "button is-info mr-2" %>
    <%= form.submit class: 'button is-primary' %>  
  </div>
<% end %>

app/views/membership_types/_membership_type.html.erb
<div id="<%= dom_id membership_type %>">
  <p>
    <strong>Code:</strong>
    <%= membership_type.code %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= membership_type.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= membership_type.price %>
  </p>

  <p>
    <strong>Organisation:</strong>
    <%= membership_type.organisation_id %>
  </p>

</div>

app/views/membership_types/edit.html.erb
<div class="container">
<h1>Editing membership type</h1>

<%= render "form", membership_type: @membership_type %>


</div>

app/views/membership_types/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Membership types</h1>

<table class="table">
  <thead>
    <tr>
    <th colspan="1"></th>
        <th>Code</th>
      <th>Description</th>
      <th>Price</th>
      <th>Organisation</th>
      </tr>
  </thead>
  <tbody>
   <% @membership_types.each do |membership_type| %>
        <tr>
          <td>
            <input type="checkbox">
          </td>
            <td><%= membership_type.code %></td>
            <td><%= membership_type.description %></td>
            <td><%= membership_type.price %></td>
            <td><%= membership_type.organisation_id %></td>
          </tr>
      <% end %>
  </tbody>
</table>

 <%= link_to 'New Membership Type', new_membership_type_path, class: "button is-succes" %>
</div>

app/views/membership_types/new.html.erb
<div class="container">

<h1>New membership type</h1>

<%= render "form", membership_type: @membership_type %>


</div>

app/views/membership_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membership_type %>

<div>
  <%= link_to "Edit this membership type", edit_membership_type_path(@membership_type) %> |
  <%= link_to "Back to membership types", membership_types_path %>

  <%= button_to "Destroy this membership type", @membership_type, method: :delete %>
</div>