config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  resources :periods
  resources :transactions do
    collection do
      post :import
    end
  end
  resources :memberships
  resources :membership_types
  resources :accounts
  resources :member_groups
  resources :invoices
  resources :members do
    collection do
      post :import
    end
  end
  resources :organisations
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :organisation
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :bankaccountable, polymorphic: true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :account
  belongs_to :period
  belongs_to :organisation
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :member
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/mandate.rb
class Mandate < ApplicationRecord
  belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :organisation
  has_one :adress, as: :addressable
  has_one :bank_account, as: :bankaccountable
end

app/models/member_group.rb
class MemberGroup < ApplicationRecord
  belongs_to :organisation
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :member
  belongs_to :membership_type
end

app/models/membership_type.rb
class MembershipType < ApplicationRecord
  belongs_to :organisation
end

app/models/organisation.rb
class Organisation < ApplicationRecord
    has_one :adress, as: :addressable
    has_one :bank_account, as: :bankaccountable
end

app/models/period.rb
class Period < ApplicationRecord
  belongs_to :organisation
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :organisation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    return redirect_to request.referer, notice: 'Geen bestand' if params[:file].nil?
    return redirect_to request.referer, notice: 'Alleen CSV bestanden zijn toegestaan' unless params[:file].content_type == 'text/csv'
    
    CsvImportTransactionService.call(params[:file])

    redirect_to request.referer, notice: 'Import transacties gestart...'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:transaction_date, :transaction_number, :transaction_amount, :description, :account_id, :organisation_id, :transaction_text, :iban, :counter_iban, :transaction_code, :transaction_type, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transaction_date, class: "label" %>
    <div class="control">
      <%= form.date_field :transaction_date, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :transaction_number, class: "label" %>
    <div class="control">
      <%= form.text_field :transaction_number, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :transaction_amount, class: "label" %>
    <div class="control">
      <%= form.text_field :transaction_amount, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :description, class: "label" %>
    <div class="control">
      <%= form.text_field :description, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :account_id, class: "label" %>
    <div class="select">
      <%= form.collection_select :account_id, Account.all, :id, :name, { prompt: true }  %>
    </div>
  </div>

  <div class="field">
    <%= form.label :organisation_id, class: "label" %>
    <div class="select">
      <%= form.collection_select :organisation_id, Organisation.all, :id, :name, { prompt: true }  %>
    </div>
  </div>

  <div class="field">
    <%= form.label :transaction_text, class: "label" %>
    <div class="control">
      <%= form.text_area :transaction_text, class: "input" %>
    </div>
  </div>

 <div class="field is-grouped">
    <%= link_to "Back", transactions_path, class: "button is-info mr-2" %>
    <%= form.submit class: 'button is-primary' %>  
  </div>
<% end %>

app/views/transactions/_import.html.erb
<%= form_tag import_transactions_path, method: :post, multipart: true do %>
    
    <div class="file">
        <label class="file-label">
            <%= file_field_tag :file, accept: ".csv" %>
            <span class="file-cta">
                <span class="file-icon">
                    <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                    Kies bestand
                </span>
            </span>
        </label>
    </div
    
    <%= submit_tag 'Import', class: "button is-primary" %>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Transaction date:</strong>
    <%= transaction.transaction_date %>
  </p>

  <p>
    <strong>Transaction number:</strong>
    <%= transaction.transaction_number %>
  </p>

  <p>
    <strong>Transaction amount:</strong>
    <%= transaction.transaction_amount %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= transaction.description %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= transaction.account_id %>
  </p>

  <p>
    <strong>Organisation:</strong>
    <%= transaction.organisation_id %>
  </p>

  <p>
    <strong>Transaction text:</strong>
    <%= transaction.transaction_text %>
  </p>

</div>

app/views/transactions/edit.html.erb
<div class="container">
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>


</div>

app/views/transactions/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>


<%= render "import" %>


<table class="table">
  <thead>
    <tr>
    <th colspan="1"></th>
    <th>Transaction number</th>
      <th>Transaction date</th>
      <th>Transaction amount</th>
      <th>Description</th>
      <th>Account</th>
      <th>Organisation</th>
      <th>Transaction text</th>
      </tr>
  </thead>
  <tbody>
   <% @transactions.each do |transaction| %>
        <tr>
          <td>
            <input type="checkbox">
          </td>
            <td><%= link_to transaction.transaction_number, edit_transaction_path(transaction.id) %></td>
            <td><%= transaction.transaction_date %></td>
            <td><%= transaction.transaction_amount %></td>
            <td><%= transaction.description %></td>
            <td><%= transaction.account_id %></td>
            <td><%= transaction.organisation_id %></td>
            <td><%= transaction.transaction_text %></td>
          </tr>
      <% end %>
  </tbody>
</table>

 <%= link_to 'New Transaction', new_transaction_path, class: "button is-succes" %>
</div>

app/views/transactions/new.html.erb
<div class="container">

<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>


</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>